### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by copy** [TechStark/emscripten-docker#1]
We'd like to use this image for CI testing, but the most latest version is too old (emscripten is moving fast!), would you mind updating to latest emscripten? I can send a PR if you're busy.

**Comment by ttt43ttt** [comment]
I'll build one using latest emsdk today.

**Comment by ttt43ttt** [comment]
The emscripten version 1.37.16 is pushed.

**Comment by copy** [comment]
Thanks! Tested and working.
